# Generated by Django 5.1 on 2024-08-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='class_time',
        ),
    ]
