# Generated by Django 5.1 on 2024-08-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='class_time',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
