# Generated by Django 5.1 on 2024-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='evolution_field',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='evolution_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
