# Generated by Django 5.1 on 2024-08-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_evolution_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_time',
            field=models.CharField(default='00:00', max_length=8),
        ),
    ]
