# Generated by Django 5.1 on 2024-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cpf_field',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
